# Generated by Django 5.2.1 on 2026-09-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(verbose_name='max_length=10')),
                ('description', models.TextField()),
                ('fullname', models.CharField(verbose_name='max_length=50')),
                ('place', models.CharField(verbose_name='max_length=50')),
            ],
        ),
    ]
