# Generated by Django 5.2.1 on 2026-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_cardescription_alter_review_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardescription',
            name='km',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardescription',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
