# Generated by Django 5.2.1 on 2026-09-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_cardescription_km_cardescription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardescription',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
