# Generated by Django 5.2.1 on 2026-09-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.CharField(max_length=20)),
                ('price_from', models.IntegerField(default=0)),
                ('price_to', models.IntegerField(default=0)),
                ('total_days', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
