# Generated by Django 5.2.1 on 2026-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_cartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardescription',
            name='image',
            field=models.ImageField(default=0, upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
