# Generated by Django 5.2.1 on 2026-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_cardescription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
