# Generated by Django 5.2.1 on 2026-10-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
