# Generated by Django 5.2.1 on 2026-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_required', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('rental_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
