# Generated by Django 5.2.1 on 2026-10-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pickup_location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='return_location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
