# Generated by Django 5.2.1 on 2026-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_contact_pickup_location_contact_return_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='passenger',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
