# Generated by Django 5.2.1 on 2026-10-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_contact_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='passenger',
            new_name='passengers',
        ),
    ]
